/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiTutorRouteImport } from './routes/ai-tutor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as JambRouteImport } from './routes/jamb'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WaecRouteImport } from './routes/waec'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as ApiPaystackInitRouteImport } from './routes/api/paystack/init'
import { Route as ApiPaystackVerifyRouteImport } from './routes/api/paystack/verify'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTutorRoute = AiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const JambRoute = JambRouteImport.update({
  id: '/jamb',
  path: '/jamb',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WaecRoute = WaecRouteImport.update({
  id: '/waec',
  path: '/waec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackInitRoute = ApiPaystackInitRouteImport.update({
  id: '/api/paystack/init',
  path: '/api/paystack/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackVerifyRoute = ApiPaystackVerifyRouteImport.update({
  id: '/api/paystack/verify',
  path: '/api/paystack/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tutor': typeof AiTutorRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/jamb': typeof JambRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/waec': typeof WaecRoute
  '/api/tutor': typeof ApiTutorRoute
  '/api/paystack/init': typeof ApiPaystackInitRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tutor': typeof AiTutorRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/jamb': typeof JambRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/waec': typeof WaecRoute
  '/api/tutor': typeof ApiTutorRoute
  '/api/paystack/init': typeof ApiPaystackInitRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-tutor': typeof AiTutorRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/jamb': typeof JambRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/waec': typeof WaecRoute
  '/api/tutor': typeof ApiTutorRoute
  '/api/paystack/init': typeof ApiPaystackInitRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tutor'
    | '/auth'
    | '/features'
    | '/jamb'
    | '/pricing'
    | '/reset-password'
    | '/waec'
    | '/api/tutor'
    | '/api/paystack/init'
    | '/api/paystack/verify'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tutor'
    | '/auth'
    | '/features'
    | '/jamb'
    | '/pricing'
    | '/reset-password'
    | '/waec'
    | '/api/tutor'
    | '/api/paystack/init'
    | '/api/paystack/verify'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/ai-tutor'
    | '/auth'
    | '/features'
    | '/jamb'
    | '/pricing'
    | '/reset-password'
    | '/waec'
    | '/api/tutor'
    | '/api/paystack/init'
    | '/api/paystack/verify'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTutorRoute: typeof AiTutorRoute
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  JambRoute: typeof JambRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WaecRoute: typeof WaecRoute
  ApiTutorRoute: typeof ApiTutorRoute
  ApiPaystackInitRoute: typeof ApiPaystackInitRoute
  ApiPaystackVerifyRoute: typeof ApiPaystackVerifyRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tutor': {
      id: '/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jamb': {
      id: '/jamb'
      path: '/jamb'
      fullPath: '/jamb'
      preLoaderRoute: typeof JambRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waec': {
      id: '/waec'
      path: '/waec'
      fullPath: '/waec'
      preLoaderRoute: typeof WaecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/init': {
      id: '/api/paystack/init'
      path: '/api/paystack/init'
      fullPath: '/api/paystack/init'
      preLoaderRoute: typeof ApiPaystackInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/verify': {
      id: '/api/paystack/verify'
      path: '/api/paystack/verify'
      fullPath: '/api/paystack/verify'
      preLoaderRoute: typeof ApiPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTutorRoute: AiTutorRoute,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  JambRoute: JambRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WaecRoute: WaecRoute,
  ApiTutorRoute: ApiTutorRoute,
  ApiPaystackInitRoute: ApiPaystackInitRoute,
  ApiPaystackVerifyRoute: ApiPaystackVerifyRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
