/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AiTutorRouteImport } from './routes/ai-tutor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as JambRouteImport } from './routes/jamb'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WaecRouteImport } from './routes/waec'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing.index'
import { Route as AuthenticatedBillingCallbackRouteImport } from './routes/_authenticated/billing.callback'
import { Route as AuthenticatedCbtIndexRouteImport } from './routes/_authenticated/cbt.index'
import { Route as AuthenticatedCbtSessionIdRouteImport } from './routes/_authenticated/cbt.$sessionId'
import { Route as AuthenticatedMaterialsIndexRouteImport } from './routes/_authenticated/materials.index'
import { Route as AuthenticatedMaterialsMaterialIdRouteImport } from './routes/_authenticated/materials.$materialId'
import { Route as AuthenticatedResultsSessionIdRouteImport } from './routes/_authenticated/results.$sessionId'
import { Route as ApiAdminGenerateQuestionsRouteImport } from './routes/api/admin/generate-questions'
import { Route as ApiCbtAnalyzeRouteImport } from './routes/api/cbt/analyze'
import { Route as ApiMaterialsGenerateRouteImport } from './routes/api/materials/generate'
import { Route as ApiPaystackInitRouteImport } from './routes/api/paystack/init'
import { Route as ApiPaystackVerifyRouteImport } from './routes/api/paystack/verify'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTutorRoute = AiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const JambRoute = JambRouteImport.update({
  id: '/jamb',
  path: '/jamb',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WaecRoute = WaecRouteImport.update({
  id: '/waec',
  path: '/waec',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingCallbackRoute =
  AuthenticatedBillingCallbackRouteImport.update({
    id: '/billing/callback',
    path: '/billing/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCbtIndexRoute = AuthenticatedCbtIndexRouteImport.update({
  id: '/cbt/',
  path: '/cbt/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCbtSessionIdRoute =
  AuthenticatedCbtSessionIdRouteImport.update({
    id: '/cbt/$sessionId',
    path: '/cbt/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialsIndexRoute =
  AuthenticatedMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialsMaterialIdRoute =
  AuthenticatedMaterialsMaterialIdRouteImport.update({
    id: '/materials/$materialId',
    path: '/materials/$materialId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsSessionIdRoute =
  AuthenticatedResultsSessionIdRouteImport.update({
    id: '/results/$sessionId',
    path: '/results/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAdminGenerateQuestionsRoute =
  ApiAdminGenerateQuestionsRouteImport.update({
    id: '/api/admin/generate-questions',
    path: '/api/admin/generate-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCbtAnalyzeRoute = ApiCbtAnalyzeRouteImport.update({
  id: '/api/cbt/analyze',
  path: '/api/cbt/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaterialsGenerateRoute = ApiMaterialsGenerateRouteImport.update({
  id: '/api/materials/generate',
  path: '/api/materials/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackInitRoute = ApiPaystackInitRouteImport.update({
  id: '/api/paystack/init',
  path: '/api/paystack/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackVerifyRoute = ApiPaystackVerifyRouteImport.update({
  id: '/api/paystack/verify',
  path: '/api/paystack/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tutor': typeof AiTutorRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/jamb': typeof JambRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/waec': typeof WaecRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/api/tutor': typeof ApiTutorRoute
  '/billing/callback': typeof AuthenticatedBillingCallbackRoute
  '/cbt/$sessionId': typeof AuthenticatedCbtSessionIdRoute
  '/materials/$materialId': typeof AuthenticatedMaterialsMaterialIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/api/admin/generate-questions': typeof ApiAdminGenerateQuestionsRoute
  '/api/cbt/analyze': typeof ApiCbtAnalyzeRoute
  '/api/materials/generate': typeof ApiMaterialsGenerateRoute
  '/api/paystack/init': typeof ApiPaystackInitRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/cbt/': typeof AuthenticatedCbtIndexRoute
  '/materials/': typeof AuthenticatedMaterialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tutor': typeof AiTutorRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/jamb': typeof JambRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/waec': typeof WaecRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/api/tutor': typeof ApiTutorRoute
  '/billing/callback': typeof AuthenticatedBillingCallbackRoute
  '/cbt/$sessionId': typeof AuthenticatedCbtSessionIdRoute
  '/materials/$materialId': typeof AuthenticatedMaterialsMaterialIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/api/admin/generate-questions': typeof ApiAdminGenerateQuestionsRoute
  '/api/cbt/analyze': typeof ApiCbtAnalyzeRoute
  '/api/materials/generate': typeof ApiMaterialsGenerateRoute
  '/api/paystack/init': typeof ApiPaystackInitRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/cbt': typeof AuthenticatedCbtIndexRoute
  '/materials': typeof AuthenticatedMaterialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-tutor': typeof AiTutorRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/jamb': typeof JambRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/waec': typeof WaecRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/api/tutor': typeof ApiTutorRoute
  '/_authenticated/billing/callback': typeof AuthenticatedBillingCallbackRoute
  '/_authenticated/cbt/$sessionId': typeof AuthenticatedCbtSessionIdRoute
  '/_authenticated/materials/$materialId': typeof AuthenticatedMaterialsMaterialIdRoute
  '/_authenticated/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/api/admin/generate-questions': typeof ApiAdminGenerateQuestionsRoute
  '/api/cbt/analyze': typeof ApiCbtAnalyzeRoute
  '/api/materials/generate': typeof ApiMaterialsGenerateRoute
  '/api/paystack/init': typeof ApiPaystackInitRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/cbt/': typeof AuthenticatedCbtIndexRoute
  '/_authenticated/materials/': typeof AuthenticatedMaterialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tutor'
    | '/auth'
    | '/features'
    | '/jamb'
    | '/pricing'
    | '/reset-password'
    | '/waec'
    | '/admin'
    | '/dashboard'
    | '/planner'
    | '/tutor'
    | '/api/tutor'
    | '/billing/callback'
    | '/cbt/$sessionId'
    | '/materials/$materialId'
    | '/results/$sessionId'
    | '/api/admin/generate-questions'
    | '/api/cbt/analyze'
    | '/api/materials/generate'
    | '/api/paystack/init'
    | '/api/paystack/verify'
    | '/api/public/paystack-webhook'
    | '/billing/'
    | '/cbt/'
    | '/materials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tutor'
    | '/auth'
    | '/features'
    | '/jamb'
    | '/pricing'
    | '/reset-password'
    | '/waec'
    | '/admin'
    | '/dashboard'
    | '/planner'
    | '/tutor'
    | '/api/tutor'
    | '/billing/callback'
    | '/cbt/$sessionId'
    | '/materials/$materialId'
    | '/results/$sessionId'
    | '/api/admin/generate-questions'
    | '/api/cbt/analyze'
    | '/api/materials/generate'
    | '/api/paystack/init'
    | '/api/paystack/verify'
    | '/api/public/paystack-webhook'
    | '/billing'
    | '/cbt'
    | '/materials'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-tutor'
    | '/auth'
    | '/features'
    | '/jamb'
    | '/pricing'
    | '/reset-password'
    | '/waec'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/planner'
    | '/_authenticated/tutor'
    | '/api/tutor'
    | '/_authenticated/billing/callback'
    | '/_authenticated/cbt/$sessionId'
    | '/_authenticated/materials/$materialId'
    | '/_authenticated/results/$sessionId'
    | '/api/admin/generate-questions'
    | '/api/cbt/analyze'
    | '/api/materials/generate'
    | '/api/paystack/init'
    | '/api/paystack/verify'
    | '/api/public/paystack-webhook'
    | '/_authenticated/billing/'
    | '/_authenticated/cbt/'
    | '/_authenticated/materials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiTutorRoute: typeof AiTutorRoute
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  JambRoute: typeof JambRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WaecRoute: typeof WaecRoute
  ApiTutorRoute: typeof ApiTutorRoute
  ApiAdminGenerateQuestionsRoute: typeof ApiAdminGenerateQuestionsRoute
  ApiCbtAnalyzeRoute: typeof ApiCbtAnalyzeRoute
  ApiMaterialsGenerateRoute: typeof ApiMaterialsGenerateRoute
  ApiPaystackInitRoute: typeof ApiPaystackInitRoute
  ApiPaystackVerifyRoute: typeof ApiPaystackVerifyRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tutor': {
      id: '/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jamb': {
      id: '/jamb'
      path: '/jamb'
      fullPath: '/jamb'
      preLoaderRoute: typeof JambRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waec': {
      id: '/waec'
      path: '/waec'
      fullPath: '/waec'
      preLoaderRoute: typeof WaecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/callback': {
      id: '/_authenticated/billing/callback'
      path: '/billing/callback'
      fullPath: '/billing/callback'
      preLoaderRoute: typeof AuthenticatedBillingCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cbt/': {
      id: '/_authenticated/cbt/'
      path: '/cbt'
      fullPath: '/cbt/'
      preLoaderRoute: typeof AuthenticatedCbtIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cbt/$sessionId': {
      id: '/_authenticated/cbt/$sessionId'
      path: '/cbt/$sessionId'
      fullPath: '/cbt/$sessionId'
      preLoaderRoute: typeof AuthenticatedCbtSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials/': {
      id: '/_authenticated/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof AuthenticatedMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials/$materialId': {
      id: '/_authenticated/materials/$materialId'
      path: '/materials/$materialId'
      fullPath: '/materials/$materialId'
      preLoaderRoute: typeof AuthenticatedMaterialsMaterialIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$sessionId': {
      id: '/_authenticated/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof AuthenticatedResultsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/admin/generate-questions': {
      id: '/api/admin/generate-questions'
      path: '/api/admin/generate-questions'
      fullPath: '/api/admin/generate-questions'
      preLoaderRoute: typeof ApiAdminGenerateQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cbt/analyze': {
      id: '/api/cbt/analyze'
      path: '/api/cbt/analyze'
      fullPath: '/api/cbt/analyze'
      preLoaderRoute: typeof ApiCbtAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/materials/generate': {
      id: '/api/materials/generate'
      path: '/api/materials/generate'
      fullPath: '/api/materials/generate'
      preLoaderRoute: typeof ApiMaterialsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/init': {
      id: '/api/paystack/init'
      path: '/api/paystack/init'
      fullPath: '/api/paystack/init'
      preLoaderRoute: typeof ApiPaystackInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/verify': {
      id: '/api/paystack/verify'
      path: '/api/paystack/verify'
      fullPath: '/api/paystack/verify'
      preLoaderRoute: typeof ApiPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedBillingCallbackRoute: typeof AuthenticatedBillingCallbackRoute
  AuthenticatedCbtSessionIdRoute: typeof AuthenticatedCbtSessionIdRoute
  AuthenticatedMaterialsMaterialIdRoute: typeof AuthenticatedMaterialsMaterialIdRoute
  AuthenticatedResultsSessionIdRoute: typeof AuthenticatedResultsSessionIdRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedCbtIndexRoute: typeof AuthenticatedCbtIndexRoute
  AuthenticatedMaterialsIndexRoute: typeof AuthenticatedMaterialsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedBillingCallbackRoute: AuthenticatedBillingCallbackRoute,
  AuthenticatedCbtSessionIdRoute: AuthenticatedCbtSessionIdRoute,
  AuthenticatedMaterialsMaterialIdRoute: AuthenticatedMaterialsMaterialIdRoute,
  AuthenticatedResultsSessionIdRoute: AuthenticatedResultsSessionIdRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedCbtIndexRoute: AuthenticatedCbtIndexRoute,
  AuthenticatedMaterialsIndexRoute: AuthenticatedMaterialsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiTutorRoute: AiTutorRoute,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  JambRoute: JambRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WaecRoute: WaecRoute,
  ApiTutorRoute: ApiTutorRoute,
  ApiAdminGenerateQuestionsRoute: ApiAdminGenerateQuestionsRoute,
  ApiCbtAnalyzeRoute: ApiCbtAnalyzeRoute,
  ApiMaterialsGenerateRoute: ApiMaterialsGenerateRoute,
  ApiPaystackInitRoute: ApiPaystackInitRoute,
  ApiPaystackVerifyRoute: ApiPaystackVerifyRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
